org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Check https://fabricmc.net/develop for the newest values if any of these fail to resolve
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.1
loom_version=1.14-SNAPSHOT

mod_version=1.0.0
maven_group=dev.nova
archives_base_name=nova-client

fabric_version=0.140.0+1.21.11
